---
id: Ldap
name: Ldap
full: LDAP client library
description: A library for connecting to LDAP servers and working with directory objects.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Ldap
authors:
  -
    name: Ben Klang
    user: bklang
    email: ben@alkaloid.net
    active: true
    role: lead
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 3.0.0alpha3
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-3.0
  uri: http://opensource.org/licenses/lgpl-3.0.html
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/util: ^3
    ext:
      ldap: '*'
  optional:
    composer:
      horde/test: ^3
